name: MacOS VNC + ngrok
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Enable VNC for default user
        env:
          VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
        run: |
          # Enable remote management
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -allowAccessFor -allUsers -privs -all
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -clientopts -setvnclegacy -vnclegacy yes

          # Set VNC password
          echo "$VNC_PASSWORD" | perl -we 'BEGIN { @k = unpack "C*", pack "H*", "1734516E8BA8C5E2FF1C39567390ADCA"}; $_ = <>; chomp; s/^(.{8}).*/$1/; @p = unpack "C*", $_; foreach (@k) { printf "%02X", $_ ^ (shift @p || 0) }; print "\n"' \
            | sudo tee /Library/Preferences/com.apple.VNCSettings.txt

          # Restart VNC service
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent -console
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate

      - name: Download ngrok CLI
        run: |
          mkdir -p $HOME/.ngrok
          curl -sSL https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-arm64.zip -o ngrok.zip
          unzip ngrok.zip -d $HOME/.ngrok
          chmod +x $HOME/.ngrok/ngrok
          echo "$HOME/.ngrok" >> $GITHUB_PATH

      - name: Authenticate ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: ngrok config add-authtoken $NGROK_AUTH_TOKEN

      - name: Start ngrok TCP tunnel
        run: nohup ngrok tcp 5900 --log=stdout > ngrok.log & sleep 5

      - name: Show ngrok public URL
        run: curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: Keep Runner Alive
        uses: mxschmitt/action-tmate@v2
